### ISSUE TITLE
Write a vue-cli plugin

### ISSUE THREAD

**Issue by ncanatta** [thisvui/thisvui#10]
Would be useful a plugin to add ThisVui to projects through vue-cli.

It should contemplate the following options:
- Choose presets: e.g. default, advanced, etc.
- Choose quick start templates
- Choose themes.
- Choose font icon libraries.
- Choose locale.

**Comment by mu545** [comment]
Hey! I will be glad to handle this issue.

my suggestion is cli placed in a different repository. to reference see [buefy cli](https://github.com/buefy/vue-cli-plugin-buefy)

**Comment by ncanatta** [comment]
Hey @mu545 !, I will appreciate it very much!.
Excellent suggestion!, I'll create the repository to place the plugin so you can fork it!.

**Comment by ncanatta** [comment]
Here is the link to the repository! [thisvui cli](https://github.com/thisvui/vue-cli-plugin-thisvui)

**Comment by ncanatta** [comment]
Issued in https://github.com/thisvui/vue-cli-plugin-thisvui/pull/1.
